/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gyo.http.client;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        InputAndOutputClient.run();
        ReaderAndWriterClient.run();
    }
}
