/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gyo.java.httpserver;

import com.sun.net.httpserver.Headers;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.util.List;

public class App {

    public static void main(String[] args) throws IOException {
        App app = new App();
        app.run();
    }

    private void run() throws IOException {
        // Listener 구현
        InetSocketAddress address = new InetSocketAddress(8080);
        HttpServer httpServer = HttpServer.create(address, 0);  // backlog는 기본값으로 설정


        // Handler 지정
        httpServer.createContext("/", exchange -> {
            showRequest(exchange);
            response("Hello, world!\n", exchange);
        });

        // root 하위 path에 대한 handler 지정
        httpServer.createContext("/sub", exchange -> {
            response("Hello, sub!\n", exchange);
        });

        // Listen
        httpServer.start();
    }

    // Request
    private void showRequest(HttpExchange exchange) throws IOException {

        // method
        String method = exchange.getRequestMethod();
        System.out.println("Method : " + method); // 메서드 출력

        // path
        URI uri = exchange.getRequestURI();
        String path = uri.getPath();
        System.out.println("uri path : " + path); // 메서드 출력

        // headers key, value
        Headers requestHeaders = exchange.getRequestHeaders(); // map
        for (String key : requestHeaders.keySet()) {
            List<String> values = requestHeaders.get(key);
            System.out.println(key + " : " + values);
        }

        // body
        InputStream inputStream = exchange.getRequestBody(); // stream으로 들어온다.
        byte[] bytes = inputStream.readAllBytes();
        String body = new String(bytes);
        System.out.println(body);
    }

    // Response
    private void response(String content, HttpExchange exchange) throws IOException {
        // Content-Lenght를 위해서 byte 배열로 변경
        byte[] contentBytes = content.getBytes();

        // Response Header : HTTP Status Code와 Content-Length 지정.
        exchange.sendResponseHeaders(200, contentBytes.length);

        // ResponseBody에 body 입력 : outputStream을 얻고, 스트림에 write
        OutputStream outputStream = exchange.getResponseBody();
        outputStream.write(contentBytes);
        outputStream.flush();
    }
    
}
