/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gyo.http.server;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Reader;
import java.io.Writer;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.CharBuffer;

public class App {

    public static void main(String[] args) throws IOException {
        App app = new App();
        app.run();
    }

    private void run() throws IOException {
        // 1. Listen
        ServerSocket listener = new ServerSocket(8080);

        System.out.println("Listen!");

        // 2. Accept
        Socket socket = listener.accept();

        System.out.println("Accept!");

        // 3. Request
        Reader reader = new InputStreamReader(socket.getInputStream());
        CharBuffer charBuffer = CharBuffer.allocate(1_000_000);
        reader.read(charBuffer);
        charBuffer.flip();  // 읽고 flip 필요
        // 읽은 요청을 출력, charBuffer의 내용(Request)에 따라서 처리할 수 있다.
        System.out.println(charBuffer);

        // 4. Response

        String body = "Hello, world!";  // HTML 작성하면 됨
        byte[] bytes = body.getBytes();
        String message = "HTTP/1.1 200 OK\n" +
                "Content-Type: text/html; charset=UTF-8\n" +
                "Content-Length: " + bytes.length + "\n" +
                "\n" +
                body;

        Writer writer = new OutputStreamWriter(socket.getOutputStream());
        writer.write(message);
        writer.flush();

        // 5. Close
        socket.close();
        listener.close();
    }
}
