/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rmi;

import java.rmi.Naming;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    private static final Logger logger = Logger.getLogger(App.class.getName());

    public static void main(String[] args) {

        try {
            HelloServer helloServer = new HelloServer();
            Naming.rebind("HelloServer", helloServer);
            System.out.println("HelloServer bound in registry");

        } catch (Exception e) {
            logger.log(Level.SEVERE, "HelloServer exception: " + e.getMessage());
        }
    }
}
